name: Run Newman Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout код репозитория
        uses: actions/checkout@v2

      - name: Установка Node.js и Newman
        uses: actions/setup-node@v2
        with:
          node-version: 14
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Запуск тестов Newman и создание отчета
        run: |
          newman run Mитап.postman_collection.json -r htmlextra --reporter-htmlextra-title "sample report"
